### ISSUE TITLE
Convert LR 2.0 envelope to JSON-LD?

### ISSUE THREAD

**Issue by science** [learningtapestry/learningregistry#11]
@aspino - the idea was raised today about converting the LR 2.0 envelope structure to JSON-LD. What do you think? It has some appeal in that the whole system would be using the same schema system. If we did, it might look like the following:

``` json
{
  "@id": "ac0c5f52-68b8-4438-bf34-6a63b1b95b56",
  "@type": "LearningRegistryEnvelope",
  "envelope_type": "resource_data",
  "envelope_version": "1.0.0",
  "envelope_id": "ac0c5f52-68b8-4438-bf34-6a63b1b95b56",
  "resource": "[resource serialized as string]",
  "resource_format": "json",
  "resource_encoding": "jwt",
  "resource_public_key": "[key]",
  "@context": [
    {
      "@vocab": "http://learningregistry.org/schema/v1/LearningRegistryEnvelope",
      "url": {
        "@type": "@id"
      }
    }
  ]
}
```

It's not totally clear to me if we need/want the `@id` field at all since envelope_id does the same thing (or should we get rid of `envelope_id`? Otherwise it seems like a pretty straight forward set of additions to our existing schema?

Worth doing?

**Comment by andersoncardoso** [comment]
@science, I guess this is deprecated, since we are already validating json-ld schemas.
I'm marking as closed, but if there is something else I'm missing here, let me know. tks
