### ISSUE TITLE
Create walkthrough's / readme's for Credential Registry

### ISSUE THREAD

**Issue by science** [learningtapestry/learningregistry#26]
- Create and publish an envelope
  - Examples for credential and envelope
  - Integration with envelope
  - Signing with JWT
  - Publishing
    - What happens when a document has an error/fails validation
- Retrieve an envelope
- Other docs / info that @andersoncardoso thinks will improve the developer experience

**Comment by andersoncardoso** [comment]
https://github.com/learningtapestry/learningregistry/blob/master/docs/credential_registry_walkthrough.md

We will improve on this iteratively.
