### ISSUE TITLE
Create roadmap for project

### ISSUE THREAD

**Issue by science** [learningtapestry/learningregistry#30]
Include sections for "core," "learning registry," and "credential registry" where there is active work or plans for each.

Probably just create a "ROADMAP.md" file for this, and include a link to it on the README.md file.

**Comment by andersoncardoso** [comment]
Done => [ROADMAP](https://github.com/learningtapestry/metadataregistry/blob/master/ROADMAP.md)
- https://github.com/learningtapestry/metadataregistry/commit/4ec53b2ca3706685b9f3822444b79744b41c9090
- https://github.com/learningtapestry/metadataregistry/commit/5d887283a207dea64921966d0a6241bbdb0ef536
