### ISSUE TITLE
CTIDs 

### ISSUE THREAD

**Issue by andersoncardoso** [learningtapestry/learningregistry#42]
We need to add some special rules to handle the ctid's (maybe we should think later on how to handle special id's inside any community resource, for now let's only solve ctid for cred-reg)
- [x] add the prop on the cr resource (credential) schema (`cti:ctid`)
- [x] check for the pattern: `urn:ctid:[guid]`
- [x] they are unique (create a uniqueness validation for the  json-schema)
- [x] `GET /api/cred-reg/ctid`, generate a new id. returns a string in form "urn:ctid:#{uuid}"

**Comment by science** [comment]
Note there will also be "CredentialID" elements (ctid is child of CredentialID). CredentialIDs can be any arbitrary ID. @stuartasutton has docs on how these two data elements are formally defined.

**Comment by stuartasutton** [comment]
Yes, the ctid [1] property is a subproperty of the credentialId [2] property. While the ctid property is intended to have a CTID, and only a CTID as a value, the credentialID can has as value any globally unique identifier following a publicly recognized format.

[1] http://www.credreg.net/page/propertiesviewer#ctid
[2] http://www.credreg.net/page/propertiesviewer#credentialId
