### ISSUE TITLE
Search/Slice documents

### ISSUE THREAD

**Issue by aspino** [learningtapestry/learningregistry#5]
- [x] Allow full text search
- [x] Allow searching/filtering by any metadata field in the user_envelope
- [x] Allow searching/filtering by any field inside the resource data
- [x] Allow date oriented retrieval (aka "list-records" in LR 1.0)
  - Apply some filters to a query, and then retrieve "everything I haven't seen yet."
- [x] Allow retrieval of metadata by specialized identifier
  - In the Credential Registry, there will be a unique identifier called a CTID, which is a kind of URN. CTI wants CR to be able to resolve this CTID. An example of that resolution in the API might look like: `/api/credentialregistry/id/urn:ctid:6726c341-7119-4ed8-bf37-efb036dd104b`
  - One challenge is to identify in the metadata schema so that it's possible to locate where the `id` field is (and what it's called) in the schema.

**Comment by science** [comment]
Identify and define search api strategy - ideally from an existing standard for api search.

**Comment by andersoncardoso** [comment]
I'll add a more detailed checklist of subtasks:
- [x] setup ES provisioning
- [x] base repository / document / query engine
- [x] rake tasks for handling the es index (reset mappings, load data)
- [x] gather a big set of real data samples for credential registry
- [x] enable different configurations for search on  each community (and their specific resource types)
- [x] build dynamic mappings from the configs (FTS)
- [x] build dynamic mappings from the configs (resource properties)
- [x] create a customizable query builder
- [x] handle full text search
- [x] handle basic envelope filters:
  - [x] filter by community
  - [x] filter by date
  - [x] filter by envelope type
  - [x] filter by resource type
- [x] filter by resource specific fields (any field)
- [x] retrieve by community/type specific identifiers
- [x] search actions on the API
  - [x] `/api/search`
  - [x] `/api/{comm}/search`
  - [x] `/api/{comm}/{type}/search`
- [x] query translator (api => query_builder)
- [x] handle pagination
- [x] create proper response object (list of envelopes instead the ES response)
- [x] docs
- [x] tests
