### ISSUE TITLE
ctdl:ipedsID : did not match the following type

### ISSUE THREAD

**Issue by mparsons1953** [learningtapestry/learningregistry#73]
Received the following error:
{"errors":["Schema for ce_registry does not exist"]}

I have attached a document with the error, json payload and envelope.
I am using:
"envelope_community":"ce_registry","
the exact same community is used with an organization publish but I don't get an error.
[Uploading Schema for ce_registry does not exist.docx…]()

**Comment by andersoncardoso** [comment]
Hi, 

I changed these fields.
The update is running on the CI and in a couple minutes will be deployed on the server.

**Comment by andersoncardoso** [comment]
@mparsons1953 
The issues seems to have changed. 

The first one regarding the duns, and ipedsID fields is fixed. 

About the new, regarding the error with "ce_registry does not exists",  can you provide the resource?  (the link on the issue description is wrong)
I tested with the one you've given before (on the previous error), and seems to work fine, but that was an Organization.  I guess you are receiving the error for a credential sub-type right?

**Comment by mparsons1953** [comment]
Sorry you were too quick for me. 
I had started with the ipedsID as an issue. I then saw the issue was related to the schema expecting a string, and we were publishing an array. 
For clarity, I will create a new issue, so this one can be closed.
