### ISSUE TITLE
Schema for ce_registry does not exist

### ISSUE THREAD

**Issue by mparsons1953** [learningtapestry/learningregistry#74]
Received the following error:
{"errors":["Schema for ce_registry does not exist"]}

I have attached a document with the error, json payload and envelope.
I am using:
"envelope_community":"ce_registry","
the exact same community is used with an organization publish but I don't get an error.
[Schema for ce_registry does not exist.docx](https://github.com/learningtapestry/metadataregistry/files/522917/Schema.for.ce_registry.does.not.exist.docx)

**Comment by andersoncardoso** [comment]
Hi @mparsons1953 

all `@type` properties are defined as **ctdl:**Something. 
The @type you are providing is `digitalBase`. This class is defined as `ctdl:DigitalBase` here: https://github.com/learningtapestry/metadataregistry/blob/master/app/schemas/ce_registry/config.json#L11

I will fix the system to provide a better message on these cases. But which naming pattern we should follow?

**Comment by andersoncardoso** [comment]
@mparsons1953 I've fixed the messages on such cases.

On the example above, the message would be: `Cannot load json-schema. The property '@type' has an invalid value 'digitalBadge'`

P.S.: I've taken the class names from here: http://credreg.net/page/typeslist
