### ISSUE TITLE
Need to handle publishing AssessmentProfile and LearningOpportunityProfile

### ISSUE THREAD

**Issue by mparsons1953** [learningtapestry/learningregistry#78]
We had talked about the probable need to be able to publish ~~assessments~~ ctdl:AssessmentProfile and ~~learning opportunities~~ ctdl:LearningOpportunitProfile as separate top level documents. We have the latter in our [json classes](https://github.com/CredentialTransparencyInitiative/domain-models/blob/master/Complete-Vocabularies/ctdl_CompleteVocabulary.json), and [schema](https://github.com/CredentialTransparencyInitiative/domain-models/blob/master/jsonSchema.json). 

I tried to publish an assessment profile and received the following error:
**Cannot load json-schema. The property '@type' has an invalid value 'ctdl:AssessmentProfile'**

What changes are necessary to enable publishing these objects?

**Comment by stuartasutton** [comment]
Please excuse if I am off base. I am still in Europe and only checking intermittently. I am confused by this, Mike, because you seem to use "assessments" and "learning opportunities" and their profiles interchangeably.  We have both ctdl:Assessment [1] and ctdl:AssessmentProfile [2] as well as ctdl:LearningOpportunity [3] and ctdl:LearningOpportunitProfile [4]. I assume here that you are talking only about [2] and [4]. Correct?

[1] http://www.credreg.net/page/propertiesviewer#Assessment
[2] http://www.credreg.net/page/propertiesviewer#AssessmentProfile
[3] http://www.credreg.net/page/propertiesviewer#LearningOpportunity
[4] http://www.credreg.net/page/propertiesviewer#LearningOpportunityProfile

**Comment by mparsons1953** [comment]
Yes, I am referring to the AssessmentProfile and LearningOpportunityProfile.
I sometimes guilty of lazy typing (ie skipping the profile suffix), and will try to be more accurate in these discussions.

**Comment by andersoncardoso** [comment]
@mparsons1953  do you have some samples (json raw metadata) for AssessmentProfile? 
I tried to grab them from http://ctitest.siuccwd.com/Search/V2?keywords=&searchType=assessment&autosearch=true
but I'm getting "Error. An error occurred while processing your request."

For LearningOpportunityProfile it worked

**Comment by ghost** [comment]
Anderson
We have been remiss in updating our test site. I will do an update shortly.

However, I think you have access to the production site. So you can depend on the site (usually) being error free.
https://credentialfinder.org

Michael Parsons
Illinois workNet (TM)
Southern Illinois University Carbondale
Direct Phone #: 217-303-5858
General Phone # 217-786-3010 x5858
Toll Free: 1-800-252-4822 x5858

**Comment by andersoncardoso** [comment]
@mparsons1953 another question:
for the schema.org  properties, such as name and description, which is the correct form: `schema:name` or `ctdl:name`. Because the serialization schema says that the `ctdl:name` is required, but the data samples have `schema:name`.

**Comment by ghost** [comment]
Anderson
I have updated our test server. However our office (where our test server is located) is having internet issues, so you may not be able to access the site for now.
As noted previously, the user id used for the test server also has access to the production site.

Sent from my Verizon, Samsung Galaxy smartphone so

-------- Original message --------

**Comment by andersoncardoso** [comment]
sorry, I forgot to mention. I grabbed some samples on https://credentialfinder.org 
they are being use as (real case) fixtures for our testing suite.
The server is up to date with these changes, so you can add and search assessment_profiles and learning_opportunity_profiles already.
