### ISSUE TITLE
Create schema definitions for key metadata elements

### ISSUE THREAD

**Issue by science** [learningtapestry/learningregistry#8]
JSON schema for envelope and LR resource metadata.
Also credential registry resource metadata types

**Comment by science** [comment]
Use json schema format
Reference: https://gist.github.com/science/4f351ee1e9e4a476d291

**Comment by andersoncardoso** [comment]
@aspino is this assignment correct ? (both names start with 'A')

**Comment by science** [comment]
Abraham and I have been talking about getting your help on these metadata
items. This "assignment" is a little premature in that we need to brief you
on the work, and make sure you have availability to take it on. It seems
like something you'd be interested in and good at (but your input always
welcome!).. More soon.. Steve

**Comment by andersoncardoso** [comment]
ok =) , will be nice to know more about LR.
tks
