### ISSUE TITLE
Search API doesn't work with resource_type=credential

### ISSUE THREAD

**Issue by ghost** [learningtapestry/learningregistry#81]
I was checking the registry contents after doing a number of publish requests from CTI. I am to get results back using the api to search for organizations, assessments, and learning opportunities, but don't get results for credentials.
The following doesn't return records:
http://lr-staging.learningtapestry.com/api/ce-registry/search?resource_type=credential&from=2016-10-20T00:00:00

All of the following do return records:
http://lr-staging.learningtapestry.com/api/ce-registry/search?resource_type=organization&from=2016-10-20T00:00:00
http://lr-staging.learningtapestry.com/api/ce-registry/search?resource_type=learning_opportunity_profile&from=2016-10-20T00:00:00

http://lr-staging.learningtapestry.com/api/ce-registry/search?resource_type=assessment_profile&from=2016-10-20T00:00:00

**Comment by andersoncardoso** [comment]
That was a regression issue after we added multiple types of credential (we were searching only for 'ctdl:Credential' instead the sub-types) 
I've fixed now, and shortly will be deployed. 

Tks for reporting this.
