### ISSUE TITLE
Creation of a test community to use for testing new version of schema

### ISSUE THREAD

**Issue by ghost** [learningtapestry/learningregistry#86]
The Nov. 17, 2016 version of the ctdl schema has many updates, and increased complexity:
[http://credreg.net/ctdl/Schema/20161117/validation/json](url)
We need to test this schema without impacting publishing on our main site. We would like to have a test community created.
Suggested community name:  ce_registry_dev

**Comment by ghost** [comment]
@andersoncardoso , @science 
I have tried to some preliminary testing of the json schema updates. I created a separate issue for questions I have regarding configuring and testing json schema. I want to start by setting a baseline, by:

- getting the test community created
- publishing the four current schemas (without changes to validate the process)
- doing some preliminary testing, to ensure all is OK
- this will clarify that any issues with follow on testing will be related to my changes, not the environment.

NOTE: I did find a few typos in the schemas that I downloaded from github. I am not sure if these would have already been corrected in the registry. Although with the extensive changes, this probably doesn't matter.

**Comment by andersoncardoso** [comment]
Hi @siuccwd, 
I'm really sorry for the delay on answering your issues. 
I should solve the test community for tomorrow, as soon as it's live I'll ping you. 

We have a related issue here: https://github.com/learningtapestry/metadataregistry/issues/71

To clarify why this is a little more tricky than it first seems: we use a file naming convention for resolving the schemas and etc. So for creating a new community we need to have the corresponding schema files and configs.
Now that we can load schemas/configs from the db, Refactoring this should be simple, but a little laborious.

The schema haven't been updated in a while. Most typos come from me 😅, sorry for those. 
Any occurrence you find, you can always warn me to solve it. It's always good being corrected by someone else to learn.

tks for your feedback.

**Comment by andersoncardoso** [comment]
@siuccwd community created
http://lr-staging.learningtapestry.com/api/ce-registry-dev/
http://lr-staging.learningtapestry.com/api/schemas/info

you can check some info, on how to update the schemas, here: 
https://github.com/learningtapestry/metadataregistry/blob/master/docs/08_schemas.md

any questions let me know.
